# Generated by Django 5.1.4 on 2025-01-08 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive_log', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobsite',
            name='user',
        ),
    ]
