# Generated by Django 5.1.4 on 2025-01-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive_log', '0003_drivelog_user_jobsite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobsite',
            name='user',
        ),
    ]
